# Generated by Django 6.0.3 on 2026-03-15 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chalet', '0001_initial'),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('invites_payants', models.PositiveIntegerField(default=0)),
                ('invites_famille', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'approbation"), ('approuvee', 'Approuvée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('numero_reservation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approbations', to='membre.membre')),
                ('chalet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalet.chalet')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membre.membre')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
