# Generated by Django 6.0.3 on 2026-03-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
