# Generated by Django 6.0.3 on 2026-03-15 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_membre', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cotisation_payee', models.BooleanField(default=False)),
                ('frais_impayes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bloque', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
