# Generated by Django 6.0.3 on 2026-03-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chalet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite_max', models.PositiveIntegerField()),
                ('localisation', models.CharField(max_length=200)),
                ('equipements', models.TextField()),
                ('services_hiver', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chalets/')),
            ],
        ),
    ]
